[profile.default]
libs = ['lib']
optimizer = true
optimizer_runs = 200
out = 'out'
solc = "0.8.24"
src = 'src'
via_ir = true

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/v3-periphery/=lib/v3-periphery/",
  "v3-core/=lib/v3-core/contracts/",
  "v3-periphery/=lib/v3-periphery/contracts/",
  "permit2/=lib/permit2/src/",
]
